name: eslint-config-storybook@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/eslint-config-storybook@ci.yml'
      - '.node-version'
      - 'config/**'
      - 'dry-run/dr-eslint-config-sc-storybook/**'
      - 'modules/shared-for-eslint-config/**'
      - 'packages/eslint-config-storybook/**'
      - 'prettier.config.js'
      - 'yarn.lock'

env:
  WORKING_DIRECTORY: ./packages/eslint-config-storybook

defaults:
  run:
    working-directory: ${{ env.WORKING_DIRECTORY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run spell-check
        run: yarn spell-check

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run type-check
        run: yarn type-check

  dry-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-matrix-node-versions

      - name: Run prepare
        run: yarn prepare

      - name: Run dry run
        run: yarn dry-run
