name: eslint-config-next@CD

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'eslint-config-sc-next/v*'

env:
  WORKING_DIRECTORY: ./packages/eslint-config-next

jobs:
  check-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: check publish
        uses: ./.github/actions/check-publish
        with:
          npm-token: ${{ secrets.NPM_AUTH_TOKEN }}

  pre-check-lint:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

  pre-check-spell-check:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run spell-check
        run: yarn spell-check

  pre-check-type-check:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: Run prepare
        run: yarn prepare

      - name: Run type-check
        run: yarn type-check

  pre-check-dry-run:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-matrix-node-versions

      - name: Run prepare
        run: yarn prepare

      - name: Run dry run
        run: yarn dry-run

  publish:
    needs: [check-publish, pre-check-lint, pre-check-spell-check, pre-check-type-check, pre-check-dry-run]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup-single-node-version

      - name: publish
        uses: ./.github/actions/publish
        with:
          npm-token: ${{ secrets.NPM_AUTH_TOKEN }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
